print("What's your name?")
myName = input()
print("Nice to meet you, " + myName)
print("What's your age?")
myAge = input()
print("So, your name is " + myName + " and you're " + myAge + " years old? It's nice to meet you!")